# Generated by Django 5.2.6 on 2025-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pendingstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstudent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
