# Generated by Django 5.2.6 on 2025-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pendingstudent_email_alter_studentinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='propelld_quote_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payu_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
