# Generated by Django 5.2.6 on 2025-09-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_propelld_quote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
